name: Normalize bank statements
on:
  push:
    branches: [ main ]
    paths: [ 'inbox/**' ]

permissions:
  contents: write

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Normalize each new file
        run: |
          mkdir -p outbox archive
          for f in inbox/*; do
            [ -f "$f" ] || continue
            python normalizer/normalize.py --input "$f" --outdir outbox
            base="$(basename "$f")"
            stamp="$(date -u +%Y%m%d_%H%M%S)"
            git mv "$f" "archive/${stamp}_${base}" || mv "$f" "archive/${stamp}_${base}"
          done

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Normalize statements" || echo "No changes"
          git push
